version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Tokyo"
    directory: "/"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "skip ci"
      prefix-development: "check ci status"
      include: "scope"
    labels:
      - "dependencies"
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
    assignees:
      - "dependabot-bot"
    reviewers:
      - "ROhta"
    versioning-strategy: increase-if-necessary
  - package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Tokyo"
    directory: "/"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "check ci status"
      include: "scope"
    labels:
      - "dependencies"
    open-pull-requests-limit: 2
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
    assignees:
      - "dependabot-bot"
    reviewers:
      - "ROhta"
