version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Tokyo"
    directory: "/application"
    allow:
      - dependency-type: "production"
    labels:
      - "dependencies"
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
    reviewers:
      - "ROhta"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
  - package-ecosystem: "terraform"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    directory: "/iac"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
    reviewers:
      - "ROhta"
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    directory: "/"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
    reviewers:
      - "ROhta"
