labels: ["bug-1 重大バグ", "bug-2 バグ", "bug-3 改善"]
body:
  - type: textarea
    id: detail
    attributes:
      label: 詳細
      description: バグは辛いですが、バグの放置はさらに辛いです。バグかもと思ったら、遠慮なくご一報を。
      placeholder: "再現手順は次の項目に記載してください。"
    validations:
      required: true
  - type: textarea
    id: prevalence
    attributes:
      label: 再現手順
      description: "ブラウザの種類、OSバージョン、発生日時等、どんなに細かくても良いので、情報をなるべく多く書いてください。"
      placeholder: "キャプチャもお願いします。"
    validations:
      required: true
