labels: ["enhance-1 破壊的変更", "enhance-2 新機能"]
body:
  - type: input
    id: title
    attributes:
      label: 概要
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: あったら嬉しい機能
      placeholder: 簡潔に記載してください
    validations:
      required: true
