name: 'Setup Node and pnpm'
description: 'コードをチェックアウトし、Node.jsとpnpmをキャッシュ付きでセットアップして依存関係をインストールします'

inputs:
  fetch-depth:
    description: '取得するコミット数。0はすべてのブランチとタグの全履歴を示します。'
    required: false
    default: '1'
  package-json-path:
    description: 'package.jsonファイルへのパス'
    required: false
    default: 'application/package.json'
  cache-dependency-path:
    description: 'pnpm-lock.yamlファイルへのパス'
    required: false
    default: 'application/pnpm-lock.yaml'
  working-directory:
    description: 'pnpmコマンドの作業ディレクトリ'
    required: false
    default: 'application'
  permissions-config:
    description: 'actions-permissions/monitorの権限設定'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1.0.2-beta7
      with:
        config: ${{ inputs.permissions-config }}
    - uses: actions/checkout@v5
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
        package_json_file: ${{ inputs.package-json-path }}
    - uses: actions/setup-node@v6
      with:
        node-version-file: ${{ inputs.package-json-path }}
        cache: "pnpm"
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm i --frozen-lockfile
