name: Add all Issues and PRs to project
on:
  issues:
    types:
      - opened
      - transferred
      - labeled
  pull_request:
    types:
      - opened
      - labeled
jobs:
  add-to-project:
    name: Add to Project
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/add-to-project@v0.6.0
        with:
          project-url: https://github.com/users/ROhta/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
