name: Pull Request Labeler

on:
  pull_request:
    branches:
      - main
    types: [review_requested, reopened, ready_for_review]

# デフォルトシェルでパイプエラーを有効化
defaults:
  run:
    shell: bash
jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
