name: Pull Request Labeler
on:
  pull_request:
    branches:
      - main
  pull_request_review:
    types: [submitted]
jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
