name: Add all Issues and PRs to project

on:
  issues:
    types: [opened, transferred, labeled]
  pull_request:
    types: [opened, labeled]

# デフォルトシェルでパイプエラーを有効化
defaults:
  run:
    shell: bash

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/ROhta/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT }}
