name: "Pull Request Labeler"
on:
  pull_request:
    branches:
      - main
  pull_request_review:
    types: [submitted]
jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
