name: Dependency Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - main

# デフォルトシェルでパイプエラーを有効化
defaults:
  run:
    shell: bash
    working-directory: "application"

jobs:
  Dependency-Review:
    if: github.event.pull_request.draft == false && github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1-beta-7
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v5
      - uses: actions/dependency-review-action@v4
  Build-Check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions: {}
    env:
      package-json-path: "application/package.json"
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1-beta-7
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: ${{ env.package-json-path }}
      - uses: actions/setup-node@v6
        with:
          node-version-file: ${{ env.package-json-path }}
          cache: 'pnpm'
          cache-dependency-path: "application/pnpm-lock.yaml"
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Build
        run: pnpm run build
