name: Auto Merge

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1-beta-7
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          use-github-auto-merge: true
          target: 'minor'
