name: Auto Merge
on:
  check_suite:
    types:
      - completed
jobs:
  Auto-Merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}