name: Dependency Review
on:
  pull_request:
    types: [review_requested, reopened, ready_for_review]
    branches:
      - main

# デフォルトシェルでパイプエラーを有効化
defaults:
  run:
    shell: bash
    working-directory: "application"

jobs:
  Dependency-Review:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
  Build-Check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions: {}
    env:
      package-json-path: "application/package.json"
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ${{ env.package-json-path }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.package-json-path }}
          check-latest: true
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Build
        run: pnpm run build
